import Head from 'next/head';
import { useRouter } from 'next/router';

import { api } from '@/utils/api';
import Layout from '@/components/layout/Layout';
import Loader from '@/components/ui/Loader';

import Profile from './Profile';
import Tabs from './Tabs';

interface ProfilePageLayoutProps {
    children: React.ReactNode;
}

const ProfilePageLayout = ({ children }: ProfilePageLayoutProps) => {
    const router = useRouter();

    const { data: profile, isLoading } = api.user.getByUsername.useQuery(
        {
            username: (router.query.userName ?? '') as string,
        },
        {
            cacheTime: 15000,
        },
    );

    return (
        <>
            <Head>
                <title>Twitter profile</title>
                <meta content='Generated by create-t3-app' name='description' />
                <link href='/favicon.ico' rel='icon' />
            </Head>
            <Layout>
                <div className='flex w-full justify-center'>
                    {isLoading ? (
                        <Loader />
                    ) : profile ? (
                        <div className='flex w-full flex-col'>
                            <Profile profile={profile} />
                            <Tabs
                                active={router.pathname}
                                username={profile.username}
                            />
                            <main>{children}</main>
                        </div>
                    ) : (
                        <p>profile not found</p>
                    )}
                </div>
            </Layout>
        </>
    );
};

export default ProfilePageLayout;
