import { type NextPage } from 'next';
import Head from 'next/head';

import Layout from '@/components/layout/Layout';

const Bookmarks: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <Head>
                <title>Twitter bookmarks</title>
                <meta content="Generated by create-t3-app" name="description" />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Layout>
                <p className="font-extrabold">bookmarks</p>
            </Layout>
        </>
    );
};

export default Bookmarks;
