import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Layout from "@/components/layout/Layout";
import Avatar from "@/components/ui/Avatar";
import { useUser } from "@/utils/globalState";
import Icon from "@/components/ui/Icon";
import BottomSidebar from "@/components/layout/BottomSidebar";
import { api } from "@/utils/api";
import WriteTuitBox from '@/components/index/WriteTuitBox';
import Tuit from "@/components/index/Tuit";
import { slideNavbarOpenStore } from "@/utils/states/slideNavbarOpen";
import Loader from "@/components/ui/Loader";

const Home: NextPage = () => {
    const user = useUser();
    const { data: session } = useSession();
    const { data: tuitsData, isLoading } = api.tuit.get.useQuery();    

    return (
        <>
            <Head>
                <title>Twitter index</title>
                <meta content="Generated by create-t3-app" name="description" />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Layout>
                <div className="xxs:hidden sticky top-0 bg-black/60 backdrop-blur-md flex items-center justify-center min-h-[56px]">
                    <button className="absolute top-3 left-4" onClick={() => slideNavbarOpenStore.set('isOpen', true)}>
                        <Avatar user={user} width={32} />
                    </button>
                    <Icon className="text-twitterBlue" name="twitter" />
                </div>
                <div className="px-4 py-2 flex items-center w-full h-14 border border-t-0 border-x border-borderGray">
                    <p className="font-extrabold">Home</p>
                </div>
                {
                    session && (
                        <div className="xxs:block hidden">
                            <WriteTuitBox />
                        </div>

                    )
                }
                {
                    isLoading && (
                        <div className="w-full flex justify-center my-5">
                            <Loader />
                        </div>
                    )
                }
                {
                    tuitsData && tuitsData.map((tuit) => (
                        <Tuit key={tuit.id} {...tuit} />
                    ))
                }
                <BottomSidebar />
            </Layout>
        </>
    );
};

export default Home;