import { type NextPage } from 'next';
import Head from 'next/head';

import Layout from '@/components/layout/Layout';

const Profile: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <Head>
                <title>Twitter profile</title>
                <meta content='Generated by create-t3-app' name='description' />
                <link href='/favicon.ico' rel='icon' />
            </Head>
            <Layout>
                <p className='font-extrabold'>profile</p>
            </Layout>
        </>
    );
};

export default Profile;
