import { type NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Layout from '@/components/layout/Layout';
import Loader from '@/components/ui/Loader';
import { api } from '@/utils/api';
import ProfilePageLayout from '@/components/profile/ProfilePageLayout';

const Profile: NextPage = () => {
    const { userName } = useRouter().query as { userName: string | undefined };
    const { data: profile, isLoading } = api.user.getByUsername.useQuery({
        username: userName ?? null,
    });

    return (
        <>
            <Head>
                <title>Twitter profile</title>
                <meta content='Generated by create-t3-app' name='description' />
                <link href='/favicon.ico' rel='icon' />
            </Head>
            <Layout>
                <div className='flex w-full justify-center'>
                    {isLoading ? (
                        <Loader />
                    ) : profile ? (
                        <ProfilePageLayout profile={profile} />
                    ) : (
                        <p>profile not found</p>
                    )}
                </div>
            </Layout>
        </>
    );
};

export default Profile;
